name: Mi Motion Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: 30 10 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        python-version: ['3.x']
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Object Start
        run: |
          pip install requests
          pmode='${{ secrets.PMODE }}'
          pkey='${{ secrets.PKEY }}'
          user='${{ secrets.USER }}'
          pwd='${{ secrets.PWD }}'
          step='${{ secrets.STEP }}'

          python3 main.py ${pmode} ${pkey} ${user} ${pwd} ${step}
